### ISSUE TITLE
Question about message format.

### ISSUE THREAD

**Issue by carlca** [kataras/golog#2]
Hello, I've just installed your Golog package and it looks good to me. No complaints about performance from me!

One question, though and it's more aesthetic than functional. Why do you have messages like `[ERRO]` and `[DBUG]` rather than the full wording of `[ERROR]` and `[DEBUG]`. 

Maybe it's just me, but I find that the incompleteness of the wording a little distracting. 

Maybe it's so that the abbrev's line up when stacked vertically, I don't know! 

Obviously, I can amend the source of `level.go`, but is there any chance of making it an option to choose between short and long versions of the messages?

Cheers,
Carl

**Comment by kataras** [comment]
Hello @carlca, thanks for commenting.

You've right, the "short" message format is because of vertical align, just visually.

I can make it to be customized, as you suggested, give me a second :)

**Comment by carlca** [comment]
I've taken the liberty of forking the code and have implemented a possible solution. Would you like me to submit it as a Pull Request?

**Comment by kataras** [comment]
@carlca I just saw your messages, I was coding the feature. It's ready, take a look at the example: https://github.com/kataras/golog/blob/master/_examples/override-level-prefix/main.go and tell me if the behavior is the wanted one. Thanks for your offer, you're free to do improvements!

**Comment by carlca** [comment]
I'm not sure how to do Pull Requests yet, but if you want to have a look at how I approached it, have a look at https://github.com/carlca/golog

I've only changed `level.go`. The idea is that you would have a config file called ~/.golog that would have a JSON content:
{
    "UseShortMessages": true
}

**Comment by carlca** [comment]
Your way is good because it gives more flexibility and control over the formatting. Also, I'm not sure how efficient my method is in terms of how it affects performance, it would depend, I guess, on how much the config file gets read. In any case, I was treating this as an exercise Go coding as much as anything. Anyhow, I'd be interested in your thoughts on my changes.
Cheers,
Carl

**Comment by kataras** [comment]
I've seen your code @carlca , it looks great for new gopher like you, good job! The problem with your code changes is not the flexibility (it's a secondary problem), the first one is that it wouldn't work because the color text should also change every time the raw text is changed. Take a look at the `errorText`, `errorTextWithColor`, `ErrorText` and  `GetTextForLevel` on the [level.go](https://github.com/kataras/blob/master/level.go) and you'll understand what I mean.

To make a pull request, you're just forking the repository , make your changes and push them via the https://github.com/kataras/iris/pulls , you'll see a button at the top of the page. Thank you for your time!

**Comment by kataras** [comment]
I've seen your code @carlca , it looks great for new gopher like you, good job! The problem with your code changes is not the flexibility (it's a secondary problem), the first one is that it wouldn't work because the color text should also change every time the raw text is changed. Take a look at the `errorText`, `errorTextWithColor`, `ErrorText` and  `GetTextForLevel` on the [level.go](https://github.com/kataras/blob/master/level.go) and you'll understand what I mean.

To make a pull request, you're just forking the repository , make your changes and push them via the https://github.com/kataras/golog/pulls , you'll see a button at the top of the page. Thank you for your time!

**Comment by kataras** [comment]
I've seen your code @carlca , it looks great for new gopher like you, good job! The problem with your code changes is not the flexibility (it's a secondary problem), the first one is that it wouldn't work because the color text should also change every time the raw text is changed. Take a look at the `errorText`, `errorTextWithColor`, `ErrorText` and  `GetTextForLevel` on the [level.go](https://github.com/kataras/golog/blob/master/level.go) and you'll understand what I mean.

To make a pull request, you're just forking the repository, make your changes and push them via the https://github.com/kataras/golog/pulls , you'll see a button at the top of the page. Thank you for your time!

**Comment by kataras** [comment]
I've seen your code @carlca , it looks great for new gopher like you, good job! The problem with your code changes is not the flexibility (it's a secondary problem), the first one is that it wouldn't work because the color text should also change every time the raw text is changed. Take a look at the `errorText`, `errorTextWithColor`, `ErrorText` and  `GetTextForLevel` on the [level.go](https://github.com/kataras/golog/blob/master/level.go) and you'll understand what I mean.

To make a pull request, you're just forking the repository, make your changes and push them via the https://github.com/kataras/golog/pulls , you'll see a button at the top of the page. Thank you for your time and don't forget to [star](https://github.com/kataras/golog/stargazers) or/and watch the repository if you liked it!
