### ISSUE TITLE
help me set this formate: 

### ISSUE THREAD

**Issue by 5nn** [kataras/golog#3]
main.go -- func main() -- line 22-- 2018/01/07 18:49:01.1111 :This is a warning message

thank u ,

**Comment by kataras** [comment]
@5nn Golog supports message hijacking, so you can output with your own format like @celsosz , a good example of this is the below (you can modify it to your specific needs):

```go	
import (
    "runtime"
    "fmt"

    "github.com/kataras/golog"
)
// [...]
app.Logger().Handle(func(l *golog.Log) bool {
	prefix := golog.GetTextForLevel(l.Level, true)
	pc, fn, line, _ := runtime.Caller(6)
	message := fmt.Sprintf("%s line %d (%s) (%s) %s: %s",
		prefix, line, runtime.FuncForPC(pc).Name(), fn, l.FormatTime(), l.Message)

	if l.NewLine {
		message += "\n"
	}

	fmt.Print(message)
	return true
})
// [...]
```

**Comment by kataras** [comment]
@5nn Golog supports message hijacking, so you can output with your own format like @celsosz , a good example of this is the below (you can modify it to your specific needs):

```go	
import (
    "runtime"
    "fmt"

    "github.com/kataras/golog"
)
// [...]
golog.Handle(func(l *golog.Log) bool { /* or myLogger:= golog.New(...); myLogger.Handle or golog.Child(...).Handle
	prefix := golog.GetTextForLevel(l.Level, true)
	pc, fn, line, _ := runtime.Caller(6)
	message := fmt.Sprintf("%s line %d (%s) (%s) %s: %s",
		prefix, line, runtime.FuncForPC(pc).Name(), fn, l.FormatTime(), l.Message)

	if l.NewLine {
		message += "\n"
	}

	fmt.Print(message)
	return true
})
// [...]
```

**Comment by virusdefender** [comment]
It's not a good idea to hard code the stack length `pc, fn, line, _ := runtime.Caller(6)`, because the it  is not fixed, for example

```go
package main
import (
    "runtime"
    "fmt"
    "github.com/kataras/golog"
)
func main () {
	golog.Handle(func(l *golog.Log) bool {
		prefix := golog.GetTextForLevel(l.Level, true)
		pc, fn, line, _ := runtime.Caller(7)
		message := fmt.Sprintf("%s line %d (%s) (%s) %s: %s",
			prefix, line, runtime.FuncForPC(pc).Name(), fn, l.FormatTime(), l.Message)

		if l.NewLine {
			message += "\n"
		}

		fmt.Print(message)
		return true
	})
	golog.Warnf("This is a warning message")
	golog.Warn("This is a warning message")
}
```

A better way is to manually check the stack frame

```
package main
import (
    "runtime"
    "fmt"
    "github.com/kataras/golog"
    "strings"
)
func main () {
	golog.Handle(func(l *golog.Log) bool {
		prefix := golog.GetTextForLevel(l.Level, true)

		// 使用 runtime.Caller(n) 如果 n 是硬编码的，就可能会获取到错误的行号
		// 比如 logger.Debug 和 logger.Debugf 等调用栈是不一样的
		// 还比如 main.go 中是直接使用了 log.DefaultLogger 而不是 GetLogger
		// 这里需要遍历一下栈信息，找到非 golog 的第一个 frame，然后作为 caller

		file := "???"
		line := 0

		pc := make([]uintptr, 64)
		n := runtime.Callers(3, pc)
		if n != 0 {
			pc = pc[:n]
			frames := runtime.CallersFrames(pc)

			for {
				frame, more := frames.Next()
				if !strings.Contains(frame.File, "github.com/kataras/golog") {
					file = frame.File
					line = frame.Line
					break
				}
				if !more {
					break
				}
			}
		}

		slices := strings.Split(file, "/")
		file = slices[len(slices)-1]

		message := fmt.Sprintf("%s %s [%s:%d] %s",
			prefix, l.FormatTime(), file, line, l.Message)

		if l.NewLine {
			message += "\n"
		}

		// fixme https://stackoverflow.com/a/14694666
		fmt.Print(message)
		return true
	})
	golog.Warnf("This is a warning message")
	golog.Warn("This is a warning message")
}
```

**Comment by kataras** [comment]
Hello @virusdefender, Sure, I am aware of it but this was introduced at [go1.9](https://golang.org/doc/go1.9#callersframes) if I remember correctly, the above part of `golog` was written before that feature. I had a plan to push this new go feature on all of my open-source projects at some point but I totally missed it because for the last months I give 100% of my time to the upcoming Iris release. I just saw this reply, and you reminded me to push it now, at least here, thanks a lot, it really helps the community :)

**Comment by kataras** [comment]
Hello @virusdefender, Sure, I am aware of it but this was introduced at [go1.9](https://golang.org/doc/go1.9#callersframes) if I remember correctly, the above code part  is just an example I gave to the user who asking how to inject the format of the log line.

However, your comment actually helps a lot for newcomers and the community, good job!

References: 
- https://golang.org/doc/go1.9#callersframes

**Comment by kataras** [comment]
Hello @virusdefender, Sure, I am aware of it but this was introduced at [go1.9](https://golang.org/doc/go1.9#callersframes) if I remember correctly, the above code part  is just an example I gave to the user who asking how to inject the format of the log line.

The code you posted above is not actually 100% correct, it outputs:

![img334](https://user-images.githubusercontent.com/22900943/59883984-799ed600-93bf-11e9-83f5-5a6ac018a6d0.png)

However, your comment actually helps a lot for newcomers and the community, good job!

> The customize output example requires update as well, I'll do it now, but don't be afraid of creating a pull request the next time.

References: 
- https://golang.org/doc/go1.9#callersframes

**Comment by kataras** [comment]
I've just found a code block I used on private project for logging **error traces**, a good resource for everyone who's reading this issue as well:

```go
var validStacks= []func(string) bool{
	func(file string) bool {
		return strings.Contains(file, "/yourapp/path")
	},
}

func RuntimeCallerStack() (s string) {
	var pcs [10]uintptr
	n := runtime.Callers(1, pcs[:])
	frames := runtime.CallersFrames(pcs[:n])

	for {
		frame, more := frames.Next()
		for _, fn := range validStacks {
			if fn(frame.File) {
				s += fmt.Sprintf("\n\t\t\t%s:%d", frame.File, frame.Line)
			}
		}

		if !more {
			break
		}
	}

	return s
}

```

**Comment by kataras** [comment]
Hello @virusdefender, Sure, I am aware of it but this was introduced at [go1.9](https://golang.org/doc/go1.9#callersframes) if I remember correctly, the above code part  is just an example I gave to the user who asking how to inject the format of the log line.

The code you posted above will not actually work inside the _examples/customize-output example (because it's part of golog path) for example:

![img334](https://user-images.githubusercontent.com/22900943/59883984-799ed600-93bf-11e9-83f5-5a6ac018a6d0.png)

This is why I prefer to target the import path of an application that we care to log from instead of excluding a path. For example, almost six months ago I used something like this on a private project for logging error traces, a good resource for everyone who's reading this issue as well:

```go
var validStacks= []func(string) bool{
	func(file string) bool {
		return strings.Contains(file, "/yourapp/path")
	},
}

func RuntimeCallerStack() (s string) {
	var pcs [10]uintptr
	n := runtime.Callers(1, pcs[:])
	frames := runtime.CallersFrames(pcs[:n])

	for {
		frame, more := frames.Next()
		for _, fn := range validStacks {
			if fn(frame.File) {
				s += fmt.Sprintf("\n\t\t\t%s:%d", frame.File, frame.Line)
			}
		}

		if !more {
			break
		}
	}

	return s
}
```

Good job, your comment actually helps a lot for newcomers and the community!

References: 
- https://golang.org/doc/go1.9#callersframes
